import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Samuel',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('123', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name:'Bolsa Grande 1',
            category:'Bolsas',
            image:'/images/_CAO9440.jpg',
            price: 150,
            countInStock: 10,
            brand:'HandMade',
            rating:4.5,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, com forro em tecido de algodão, formato retangular',
        },
        {
            name:'Bolsa Meia Lua 1',
            category:'Bolsas',
            image:'/images/_CAO9448.jpg',
            price: 80,
            countInStock: 20,
            brand:'HandMade',
            rating:4.5,
            numReviews: 10,
            description: 'Bolsa de mão em fibra de Buriti, com forro em tecido de algodão, formato meia lua.',
        },
        {
            name:'Bolsa Média Macramê',
            category:'Bolsas',
            image:'/images/_CAO9464.jpg',
            price: 150,
            countInStock: 0,
            brand:'HandMade',
            rating:4.0,
            numReviews: 10,
            description: 'Bolsa com trama macramê em fibra de Buriti, com forro em tecido de algodão, formato retangular.',
        },
        {
            name:'Bolsa Grande 3',
            category:'Bolsas',
            image:'/images/_CAO9470.jpg',
            price: 150,
            countInStock: 30,
            brand:'HandMade',
            rating:4.5,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, com forro em tecido de algodão, retangular',
        },
        {
            name:'Bolsa meia lua 2',
            category:'Bolsas',
            image:'/images/_CAO9482.jpg',
            price: 80,
            countInStock: 10,
            brand:'HandMade',
            rating:5.0,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, com forro em tecido de algodão, alça longa , formato meia lua.',
        },
        {
            name:'Bolsa coquinho',
            category:'Bolsas',
            image:'/images/_CAO9486.jpg',
            price: 80,
            countInStock: 20,
            brand:'HandMade',
            rating:5.0,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, sem forro, alça longa , formato redonda.',
        },

    ],
};
export default data;