const data = {
    product:[
        {
            _id:'1',
            name:'Bolsa Grande 1',
            category:'Bolsas',
            image:'/images/_CAO9440.jpg',
            price: 150,
            countInStock: 10,
            brand:'HandMade',
            rating:4.5,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, com forro em tecido de algodão, formato retangular',
        },
        {
            _id:'2',
            name:'Bolsa Meia Lua 1',
            category:'Bolsas',
            image:'/images/_CAO9448.jpg',
            price: 80,
            countInStock: 20,
            brand:'HandMade',
            rating:4.5,
            numReviews: 10,
            description: 'Bolsa de mão em fibra de Buriti, com forro em tecido de algodão, formato meia lua.',
        },
        {
            _id:'3',
            name:'Bolsa Média Macramê',
            category:'Bolsas',
            image:'/images/_CAO9461.jpg',
            price: 150,
            countInStock: 0,
            brand:'HandMade',
            rating:4.0,
            numReviews: 10,
            description: 'Bolsa com trama macramê em fibra de Buriti, com forro em tecido de algodão, formato retangular.',
        },
        {
            _id:'4',
            name:'Bolsa Grande 3',
            category:'Bolsas',
            image:'/images/_CAO9470.jpg',
            price: 150,
            countInStock: 30,
            brand:'HandMade',
            rating:4.5,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, com forro em tecido de algodão, retangular',
        },
        {
            _id:'5',
            name:'Bolsa meia lua 2',
            category:'Bolsas',
            image:'/images/_CAO9479.jpg',
            price: 80,
            countInStock: 10,
            brand:'HandMade',
            rating:5.0,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, com forro em tecido de algodão, alça longa , formato meia lua.',
        },
        {
            _id:'6',
            name:'Bolsa coquinho',
            category:'Bolsas',
            image:'/images/_CAO9486.jpg',
            price: 80,
            countInStock: 20,
            brand:'HandMade',
            rating:5.0,
            numReviews: 10,
            description: 'Bolsa em fibra de Buriti, sem forro, alça longa , formato redonda.',
        },

    ],
};
export default data;